apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: flaskcalc-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flaskcalc
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50