apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: flaskcalc-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flaskcalc
  updatePolicy:
    updateMode: "Auto"